apiVersion: 1
datasources:
  - name: InfluxDB
    type: influxdb
    access: proxy
    url: http://influxdb:8086
    database: s4t_iot
    user: admin
    secureJsonData:
      password: admin
    jsonData:
      httpMode: GET
    isDefault: true
    editable: false
